#!/usr/bin/env node
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');const{spawn}=require('node:child_process');
const baseUrl='https://www.infofeina.com',dataRoot=process.env.DATA_DIR||__dirname,outputFile=path.join(dataRoot,'jobs.json');
const directUrl=String(process.env.INFOFEINA_URL||'').trim(),keyword=String(process.env.INFOFEINA_KEYWORD||'').trim().slice(0,120),city=String(process.env.INFOFEINA_CITY||'').trim().slice(0,120);const delayMs=clamp(process.env.INFOFEINA_DELAY_MS,750,500,10000),maximumPages=clamp(process.env.INFOFEINA_MAX_PAGES,100,1,500);
function clamp(v,f,min,max){const n=Number(v);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.floor(n))):f}const wait=ms=>new Promise(r=>setTimeout(r,ms));
function decodeHtml(v){const named={amp:'&',quot:'"',apos:"'",lt:'<',gt:'>',nbsp:' '};return String(v||'').replace(/&(#x[\da-f]+|#\d+|[a-z]+);/gi,(m,e)=>{if(e[0]==='#'){const n=e[1].toLowerCase()==='x'?parseInt(e.slice(2),16):parseInt(e.slice(1),10);return Number.isFinite(n)?String.fromCodePoint(n):m}return named[e.toLowerCase()]??m})}function plainText(v){return decodeHtml(String(v||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim()}
function cleanInfofeinaUrl(v,listingOnly=false){if(!String(v||'').trim())return'';try{const u=new URL(v,baseUrl);if(u.protocol!=='https:'||!/(^|\.)infofeina\.com$/i.test(u.hostname))return'';if(listingOnly&&!/^\/cercador-ofertes-feina\/?$/i.test(u.pathname))return'';u.hash='';return u.toString()}catch{return''}}
function buildSearchUrl(s={}){if(s.url){const u=cleanInfofeinaUrl(s.url,true);if(!u)throw Error('la URL debe ser un listado de Infofeina');return u}const u=new URL('/cercador-ofertes-feina',baseUrl);if(s.keyword)u.searchParams.set('title',String(s.keyword).trim());if(s.city)u.searchParams.set('location',String(s.city).trim());u.searchParams.set('radius','30');return u.toString()}
function cleanOfferUrl(v){const u=cleanInfofeinaUrl(v);if(!u)return'';return /^\/ofertes\//i.test(new URL(u).pathname)?u:''}
function parseListing(html){const start=html.indexOf('<div class="offers-list">'),end=start>=0?html.indexOf('<div class="full-width">\n                                        <p class="total-offer-txt">',start):-1,region=start>=0?html.slice(start,end>start?end:html.length):'';const blocks=region.split(/<div class="post-wrapper[^>]*>/i).slice(1);const jobs=blocks.map(b=>{const tm=b.match(/<a\s+href=["']([^"']+)["'][^>]*class=["']job_title["'][^>]*>([\s\S]*?)<\/a>/i),url=cleanOfferUrl(tm?.[1]),id=url?new URL(url).pathname.split('/').filter(Boolean).at(-1):'';const company=plainText(b.match(/class=["']company_title["'][\s\S]*?<span>([\s\S]*?)<\/span>/i)?.[1]),location=plainText(b.match(/class=["']job_location["'][^>]*>([\s\S]*?)<\/p>/i)?.[1]),description=plainText(b.match(/class=["']job_description["'][^>]*>([\s\S]*?)<\/p>/i)?.[1]),tags=[...b.matchAll(/class=["']job_tag[^"']*["'][^>]*>([\s\S]*?)<\/p>/gi)].map(m=>plainText(m[1])),date=tags.find(x=>/^\d{2}\/\d{2}\/\d{4}$/.test(x)),workday=tags.find(x=>/jornada|indiferent/i.test(x))||'';return{source:'Infofeina',source_id:id,slug:`infofeina-${id}`,title:plainText(tm?.[2]),company,author:company,description,url,country:'España',countries:['España'],location,modality:/teletreball|remot/i.test(b)?'Teletrabajo':'',workday,salary:'No indicado',budget:'No indicado',budget_eur_min:null,budget_eur_max:null,salary_period:null,language:'ca',published_at:date?`${date.slice(6)}-${date.slice(3,5)}-${date.slice(0,2)}`:null,published_label:'',urgent:false,minimumStudies:'',minimumExperience:'',requiredLanguages:[],infofeinaDetailLoaded:false}}).filter(j=>j.source_id&&j.title&&j.url);const total=Number(html.match(/Hem trobat\s+([\d.]+)\s+ofertes/i)?.[1]?.replace(/\./g,''))||jobs.length,pages=Math.max(1,...[...html.matchAll(/[?&](?:amp;)?page=(\d+)/gi)].map(m=>Number(m[1])));return{jobs,total,pages}}
function sanitizeDescriptionHtml(value){const allowed=new Set(['p','strong','b','em','i','u','ul','ol','li','br']);return String(value||'').replace(/<!--[\s\S]*?-->/g,'').replace(/<(script|style)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,'').replace(/<[^>]*>/g,tag=>{const m=tag.match(/^<\s*(\/?)\s*([a-z0-9]+)[^>]*>$/i);if(!m||!allowed.has(m[2].toLowerCase()))return'';const name=m[2].toLowerCase();return name==='br'?'<br>':`<${m[1]?'/':''}${name}>`}).trim()}
function betweenClasses(html,startClass,endClass){const source=String(html),start=source.search(new RegExp(`<div\\b[^>]*class=["'][^"']*${startClass}[^"']*["']`,'i'));if(start<0)return'';const tail=source.slice(start),end=endClass?tail.slice(1).search(new RegExp(`<div\\b[^>]*class=["'][^"']*${endClass}[^"']*["']`,'i')):-1;return end>=0?tail.slice(0,end+1):tail}
function parseDetail(html){const source=String(html);const condition=name=>plainText(source.match(new RegExp(`<p\\b[^>]*class=["'][^"']*condition-title[^"']*["'][^>]*>\\s*${name}\\s*<\\/p>\\s*<p\\b[^>]*class=["'][^"']*condition-desc[^"']*["'][^>]*>([\\s\\S]*?)<\\/p>`,'i'))?.[1]);const detailRegion=betweenClasses(source,'latest-search-sec','description-detail-wrap formation-box'),parts=[...detailRegion.matchAll(/<p\b[^>]*class=["'][^"']*description-detail["'][^>]*>([\s\S]*?)<\/p>/gi)].map(m=>m[1]);const description=parts.map(plainText).filter(Boolean).join('\n\n'),descriptionHtml=parts.map(part=>`<p>${sanitizeDescriptionHtml(part)}</p>`).join('');const studiesRegion=betweenClasses(source,'description-detail-wrap formation-box','description-detail-wrap experience-box'),minimumStudies=[...studiesRegion.matchAll(/<p\b[^>]*class=["'][^"']*detail-rgt[^"']*["'][^>]*>([\s\S]*?)<\/p>/gi)].map(m=>plainText(m[1])).filter(Boolean).join('; ');const experienceRegion=betweenClasses(source,'description-detail-wrap experience-box','description-detail-wrap lang-wrap'),years=plainText(experienceRegion.match(/Anys d(?:'|&apos;)experiència<\/p>\s*<p\b[^>]*class=["'][^"']*detail-rgt[^"']*["'][^>]*>([\s\S]*?)<\/p>/i)?.[1]),level=plainText(experienceRegion.match(/Nivell d(?:'|&apos;)experiència<\/p>\s*<p\b[^>]*class=["'][^"']*detail-rgt[^"']*["'][^>]*>([\s\S]*?)<\/p>/i)?.[1]);const languageRegion=betweenClasses(source,'description-detail-wrap lang-wrap','other-information'),requiredLanguages=[...languageRegion.matchAll(/<p\b[^>]*class=["'][^"']*language_skill[^"']*["'][^>]*>([\s\S]*?)<\/p>\s*<p\b[^>]*class=["'][^"']*percent-status[^"']*["'][^>]*>([\s\S]*?)<\/p>/gi)].map(m=>`${plainText(m[1])}: ${plainText(m[2])}`);const salary=condition('Salari')||'No indicado',workday=condition('Jornada')||plainText(source.match(/<p\b[^>]*class=["'][^"']*job_tag time[^"']*["'][^>]*>([\s\S]*?)<\/p>/i)?.[1]);return{description,descriptionHtml,workday,schedule:condition('Horari'),salary,budget:salary,contractType:condition('Tipus de contracte'),jobProspect:condition('Perspectiva de la feina'),minimumStudies,minimumExperience:[years,level].filter(Boolean).join(' · '),requiredLanguages,infofeinaDetailLoaded:true}}
function parseInfofeinaDetail(html){const detail=parseDetail(html),hasOwnWorkday=/<p\b[^>]*class=["'][^"']*condition-title[^"']*["'][^>]*>\s*Jornada\s*<\/p>/i.test(String(html)),parts=[hasOwnWorkday?detail.workday:'',detail.contractType,detail.schedule].filter(Boolean);delete detail.contractType;delete detail.schedule;delete detail.jobProspect;return{...detail,workday:parts.join(' · ')}}
async function fetchHtml(u){let last;for(let a=1;a<=3;a++)try{const r=await fetch(u,{headers:{Accept:'text/html,application/xhtml+xml','Accept-Language':'ca,es;q=0.9','User-Agent':'web-trabajos/1.0 (panel local de empleo)'},signal:AbortSignal.timeout(45000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.text()}catch(e){last=e;if(a<3)await wait(delayMs*a*2)}throw last}
async function runSearch(s){const first=new URL(buildSearchUrl(s));first.searchParams.delete('page');const jobs=new Map;let total=null,pages=1;for(let page=1;page<=Math.min(pages,maximumPages);page++){const u=new URL(first);if(page>1)u.searchParams.set('page',String(page));process.stderr.write(`Infofeina: descargando página ${page}${pages>1?`/${pages}`:''}…\n`);const p=parseListing(await fetchHtml(u));total??=p.total;pages=p.pages;for(const j of p.jobs)jobs.set(j.source_id,j);if(page<pages)await wait(delayMs)}return{jobs:[...jobs.values()],total,pages:Math.min(pages,maximumPages),complete:pages<=maximumPages,url:first.toString()}}
async function writeJson(f,v){const t=`${f}.tmp`;await fs.promises.writeFile(t,`${JSON.stringify(v,null,2)}\n`);await fs.promises.rename(t,f)}
async function main(){const r=await runSearch({url:directUrl,keyword,city}),d={scraped_at:new Date().toISOString(),source:r.url,method:'public-html',complete:r.complete,pages_scraped:r.pages,total_elements_at_start:r.total,unique_records:r.jobs.length,jobs:r.jobs};await fs.promises.mkdir(dataRoot,{recursive:true});await writeJson(outputFile,d);process.stdout.write(`${JSON.stringify({source:'Infofeina',complete:r.complete,pages_scraped:r.pages,unique_records:r.jobs.length,total_elements_at_start:r.total,scraped_at:d.scraped_at})}\n`)}
async function runChild(s,d){await new Promise((res,rej)=>{const c=spawn(process.execPath,[__filename],{env:{...process.env,DATA_DIR:d,INFOFEINA_SEARCHES:'',INFOFEINA_URL:s.url||'',INFOFEINA_KEYWORD:s.keyword||'',INFOFEINA_CITY:s.city||''},stdio:['ignore','pipe','pipe']});c.stdout.on('data',x=>process.stderr.write(x));c.stderr.on('data',x=>process.stderr.write(x));c.on('error',rej);c.on('close',n=>n===0?res():rej(Error(`la búsqueda terminó con código ${n}`)))})}
async function mainBatch(){let ss;try{ss=JSON.parse(process.env.INFOFEINA_SEARCHES||'[]')}catch{throw Error('las búsquedas de Infofeina no son válidas')}if(!Array.isArray(ss)||!ss.length)return main();const jobs=new Map,completed=[];for(const s of ss.slice(0,20)){const d=await fs.promises.mkdtemp(path.join(os.tmpdir(),'web-trabajos-infofeina-'));try{await runChild(s,d);const doc=JSON.parse(await fs.promises.readFile(path.join(d,'jobs.json'),'utf8'));for(const j of doc.jobs||[])jobs.set(j.source_id,j);completed.push({url:s.url||'',keyword:s.keyword||'',city:s.city||'',total_elements:doc.total_elements_at_start||0})}finally{await fs.promises.rm(d,{recursive:true,force:true})}}const doc={scraped_at:new Date().toISOString(),source:`${baseUrl}/cercador-ofertes-feina`,queries:completed,method:'public-html',complete:true,unique_records:jobs.size,jobs:[...jobs.values()]};await writeJson(outputFile,doc);process.stdout.write(`${JSON.stringify({source:'Infofeina',searches:completed.length,unique_records:jobs.size,scraped_at:doc.scraped_at})}\n`)}
function hasBatchSearches(v){try{const s=JSON.parse(v||'[]');return Array.isArray(s)&&s.length>0}catch{return false}}if(require.main===module)(hasBatchSearches(process.env.INFOFEINA_SEARCHES)?mainBatch():main()).catch(e=>{process.stderr.write(`Infofeina: ${e.message}\n`);process.exitCode=1});module.exports={buildSearchUrl,cleanInfofeinaUrl,parseDetail:parseInfofeinaDetail,parseListing,plainText,sanitizeDescriptionHtml};
