#!/usr/bin/env node
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');const{spawn}=require('node:child_process');
const baseUrl='https://feinaactiva.gencat.cat',dataRoot=process.env.DATA_DIR||__dirname,outputFile=path.join(dataRoot,'jobs.json');
function cleanUrl(v,listing=false){if(!String(v||'').trim())return'';try{const u=new URL(v,baseUrl);if(u.protocol!=='https:'||u.hostname!=='feinaactiva.gencat.cat')return'';if(listing&&!/^\/(?:es|ca)\/search\/offers\/list$/i.test(u.pathname))return'';u.hash='';return u.toString()}catch{return''}}
function safeOfferUrl(v){if(!String(v||'').trim())return'';try{const u=new URL(v,baseUrl);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return'';u.hash='';return u.toString()}catch{return''}}
function buildSearchUrl(s={}){if(s.url){const u=cleanUrl(s.url,true);if(!u)throw Error('la URL debe ser un listado de Feina Activa');return u}const u=new URL('/es/search/offers/list',baseUrl),term=[s.keyword,s.city].map(v=>String(v||'').trim()).filter(Boolean).join(' ');if(term)u.searchParams.set('keywords',term);return u.toString()}
function normalize(raw){const url=safeOfferUrl(raw.url),parsed=url?new URL(url):null,internal=parsed?.hostname==='feinaactiva.gencat.cat'&&/^\/(?:es|ca)\/search\/offers\/detail\//i.test(parsed.pathname),id=internal?parsed.pathname.split('/').filter(Boolean).at(-1):url;const details=String(raw.details||'');return{source:'Feina Activa',source_id:id,slug:`feinaactiva-${id}`,title:String(raw.title||'').trim(),company:String(raw.company||'').trim(),author:String(raw.company||'').trim(),description:String(raw.description||'').trim(),url,country:'España',countries:['España'],location:String(raw.location||'').trim(),modality:/teletrabajo|teletreball|remot/i.test(details)?'Teletrabajo':'',workday:details.match(/Jornada[^,.]*/i)?.[0]||'',salary:details.match(/Salario[^.]+/i)?.[0]||'No indicado',budget:details.match(/Salario[^.]+/i)?.[0]||'No indicado',budget_eur_min:null,budget_eur_max:null,salary_period:null,language:'es',published_at:null,published_label:String(raw.published||'').trim(),urgent:false,minimumStudies:'',minimumExperience:details.match(/Experiencia[^,.]*/i)?.[0]||'',requiredLanguages:[],feinaActivaDetailLoaded:!internal}}
async function scrape(search){const executablePath=process.env.CHROMIUM_PATH||['/usr/bin/chromium','/usr/bin/google-chrome',path.join(os.homedir(),'.local/opt/google-chrome/opt/google/chrome/google-chrome')].find(fs.existsSync);if(!executablePath)throw Error('se necesita Chromium para cargar el listado completo');const browser=await require('puppeteer-core').launch({executablePath,headless:true,args:['--no-sandbox','--disable-setuid-sandbox','--disable-dev-shm-usage']});try{const page=await browser.newPage();await page.setUserAgent('web-trabajos/1.0 (panel local de empleo)');await page.goto(buildSearchUrl(search),{waitUntil:'networkidle2',timeout:60000});await page.waitForSelector('fa-result-list .list-counter',{timeout:30000});await page.evaluate(()=>{const accept=[...document.querySelectorAll('ngb-modal-window button, ngb-modal-window a')].find(el=>/^Aceptar$/i.test(el.textContent.trim()));accept?.click()});await new Promise(resolve=>setTimeout(resolve,500));const totals=await page.evaluate(()=>({total:Number(document.querySelector('fa-result-list .list-counter strong')?.textContent)||0,count:document.querySelectorAll('fa-result-list [role="listitem"]').length}));let stable=0,last=totals.count;for(let attempt=0;attempt<80&&stable<10&&(!totals.total||last<totals.total);attempt++){await page.mouse.wheel({deltaY:900});await new Promise(resolve=>setTimeout(resolve,300));const count=await page.$$eval('fa-result-list [role="listitem"]',items=>items.length);stable=count===last?stable+1:0;last=count}const result=await page.evaluate(()=>{const selector='fa-result-list [role="listitem"]',total=Number(document.querySelector('fa-result-list .list-counter strong')?.textContent)||0,items=[...document.querySelectorAll(selector)].map(el=>({url:el.querySelector('a.title')?.href,title:el.querySelector('a.title')?.textContent,published:el.querySelector('.published')?.textContent,company:el.querySelector('.business')?.textContent,location:el.querySelector('.location')?.textContent,details:el.querySelector('p.description')?.textContent,description:[...el.querySelectorAll('p')].find(p=>p!==el.querySelector('p.description'))?.textContent||''}));return{total,items}});const jobs=new Map(result.items.map(x=>{const j=normalize(x);return[j.source_id,j]}));return{jobs:[...jobs.values()].filter(j=>j.source_id&&j.title&&j.url),total:result.total,url:buildSearchUrl(search)}}finally{await browser.close()}}
function plain(v){return String(v||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p\s*>/gi,'\n\n').replace(/<\/li\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
function escapeHtml(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function richText(v){const lines=plain(v).split('\n'),out=[];let list=[];const flush=()=>{if(list.length){out.push(`<ul>${list.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`);list=[]}};for(const line of lines){const value=line.trim();if(!value){flush();continue}const bullet=value.match(/^[-•]\s*(.+)$/);if(bullet){list.push(bullet[1]);continue}flush();out.push(`<p>${escapeHtml(value).replace(/^([^:]{2,60}:)(?=\s|$)/,'<strong>$1</strong>')}</p>`)}flush();return out.join('')}
function parseDetail(h){
  const sections=[...String(h).matchAll(/<fa-extra-description[^>]*>[\s\S]*?<h3[^>]*>([^<]+)<\/h3>([\s\S]*?)<\/fa-extra-description>/gi)].map(m=>({title:plain(m[1]),html:m[2],text:plain(m[2]),items:[...m[2].matchAll(/<li\b[^>]*>([\s\S]*?)<\/li>/gi)].map(x=>plain(x[1])).filter(Boolean)}));
  const descriptionSections=sections.filter(s=>/Descripci[oó]n|Detalle/i.test(s.title));
  const description=descriptionSections.map(s=>s.text).filter(Boolean).join('\n\n');
  const descriptionHtml=descriptionSections.map(s=>richText(s.text)).join('');
  const requirements=sections.find(s=>/Requisitos/i.test(s.title))?.items||[];
  const conditions=sections.find(s=>/Condiciones/i.test(s.title))?.items||[];
  const minimumExperience=requirements.find(x=>/^Experiencia\b/i.test(x))||'';
  const minimumStudies=requirements.find(x=>/^(?:Estudios?|ESO\b|Bachiller|T[ií]tulo|Formaci[oó]n|Licenciatura|Diplomatura|Grado\b)/i.test(x))||'';
  const requiredLanguages=requirements.filter(x=>/^(?:Idiomas?|Catal[aá]n|Castellano|Español|Ingl[eé]s|Franc[eé]s)\b/i.test(x));
  const jornada=conditions.find(x=>/^Jornada\b/i.test(x))||'';
  const salary=conditions.find(x=>/^Salario\b/i.test(x))||'No indicado';
  const contractType=conditions.find(x=>/^Contrato\b/i.test(x))||'';
  const modality=conditions.find(x=>/^(?:Modalidad|Teletrabajo|Trabajo (?:híbrido|remoto))/i.test(x))||'';
  const workday=[jornada,contractType].filter(Boolean).join(' · ');
  return{description,descriptionHtml,minimumExperience,minimumStudies,requiredLanguages,workday,salary,budget:salary,contractType,modality,feinaActivaDetailLoaded:true}
}
async function write(file,v){const t=`${file}.tmp`;await fs.promises.writeFile(t,`${JSON.stringify(v,null,2)}\n`);await fs.promises.rename(t,file)}
async function main(){const r=await scrape({url:process.env.FEINAACTIVA_URL||'',keyword:process.env.FEINAACTIVA_KEYWORD||'',city:process.env.FEINAACTIVA_CITY||''}),d={scraped_at:new Date().toISOString(),source:r.url,method:'public-browser-html',complete:r.jobs.length>=r.total,total_elements_at_start:r.total,unique_records:r.jobs.length,jobs:r.jobs};await fs.promises.mkdir(dataRoot,{recursive:true});await write(outputFile,d);process.stdout.write(`${JSON.stringify({source:'Feina Activa',complete:d.complete,unique_records:r.jobs.length,total_elements_at_start:r.total,scraped_at:d.scraped_at})}\n`)}
async function child(s,d){await new Promise((res,rej)=>{const c=spawn(process.execPath,[__filename],{env:{...process.env,DATA_DIR:d,FEINAACTIVA_SEARCHES:'',FEINAACTIVA_URL:s.url||'',FEINAACTIVA_KEYWORD:s.keyword||'',FEINAACTIVA_CITY:s.city||''},stdio:['ignore','pipe','pipe']});c.stdout.on('data',x=>process.stderr.write(x));c.stderr.on('data',x=>process.stderr.write(x));c.on('error',rej);c.on('close',n=>n===0?res():rej(Error(`la búsqueda terminó con código ${n}`)))})}
async function batch(){let ss;try{ss=JSON.parse(process.env.FEINAACTIVA_SEARCHES||'[]')}catch{throw Error('las búsquedas de Feina Activa no son válidas')}if(!Array.isArray(ss)||!ss.length)return main();const jobs=new Map;for(const s of ss.slice(0,20)){const d=await fs.promises.mkdtemp(path.join(os.tmpdir(),'web-trabajos-feinaactiva-'));try{await child(s,d);const doc=JSON.parse(await fs.promises.readFile(path.join(d,'jobs.json'),'utf8'));for(const j of doc.jobs||[])jobs.set(j.source_id,j)}finally{await fs.promises.rm(d,{recursive:true,force:true})}}const doc={scraped_at:new Date().toISOString(),source:`${baseUrl}/es/search/offers/list`,method:'public-browser-html',complete:true,unique_records:jobs.size,jobs:[...jobs.values()]};await write(outputFile,doc);process.stdout.write(`${JSON.stringify({source:'Feina Activa',unique_records:jobs.size,scraped_at:doc.scraped_at})}\n`)}
function has(v){try{const s=JSON.parse(v||'[]');return Array.isArray(s)&&s.length}catch{return false}}if(require.main===module)(has(process.env.FEINAACTIVA_SEARCHES)?batch():main()).catch(e=>{process.stderr.write(`Feina Activa: ${e.message}\n`);process.exitCode=1});module.exports={buildSearchUrl,cleanUrl,normalize,parseDetail};
